#!/usr/bin/env python3
"""
Plot noise sweep results: life ratio, energy change, success rate
across all 36 experiments (position + rotation).

Reads the 36 comparison txt files generated by compare_metrics.py
and produces 24 plots (6 dimensions x 4 chart types).

Usage:
    cd LIBERO
    python analyze/plot_noise_sweep.py
"""

import pathlib
import re
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ─── Paths ───────────────────────────────────────────────────────────
RESULTS_DIR = pathlib.Path("./results")
PLOTS_DIR = pathlib.Path("./plots/noise_sweep")
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

# ─── Dimension metadata ─────────────────────────────────────────────
SUFFIX_TO_DIM = {
    "par_dim0": "action.x",
    "par_dim1": "action.y",
    "par_dim2": "action.z",
    "par_rot0": "action.axis_angle1",
    "par_rot1": "action.axis_angle2",
    "par_rot2": "action.axis_angle3",
}

DIM_LABELS = {
    "action.x": "action.x",
    "action.y": "action.y",
    "action.z": "action.z",
    "action.axis_angle1": "action.axis_angle1 (roll)",
    "action.axis_angle2": "action.axis_angle2 (pitch)",
    "action.axis_angle3": "action.axis_angle3 (yaw)",
}

POSITION_DIMS = ["action.x", "action.y", "action.z"]
ROTATION_DIMS = ["action.axis_angle1", "action.axis_angle2", "action.axis_angle3"]

JOINT_COLORS = [
    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
    "#9467bd", "#8c564b", "#e377c2",
]


# ─── Parsing ─────────────────────────────────────────────────────────
def identify_file(filename: str):
    """Extract (dimension_key, noise_scale) from a comparison txt filename."""
    for suffix, dim_key in SUFFIX_TO_DIM.items():
        if suffix in filename:
            m = re.search(r"noise_(\d+)", filename)
            if m:
                return dim_key, int(m.group(1)) / 10000.0
    return None, None


def parse_comparison_file(filepath: pathlib.Path) -> dict:
    """Parse one comparison txt file → dict of metrics."""
    text = filepath.read_text(errors="replace")
    result = {}

    # ── Success rates ──
    m_b = re.search(r"Before \(No Noise\):\s+([\d.]+)%\s+\((\d+)/(\d+)", text)
    m_a = re.search(r"After \(With Noise\):\s+([\d.]+)%\s+\((\d+)/(\d+)", text)
    if m_b:
        result["success_before"] = float(m_b.group(1))
    if m_a:
        result["success_after"] = float(m_a.group(1))

    # ── Energy deltas ──
    m_draw = re.search(
        r"energy_draw\.sum\s+\|.*?\|\s+Δ\s+([+\-]?[\d.]+)%", text
    )
    m_regen = re.search(
        r"energy_regen\.sum\s+\|.*?\|\s+Δ\s+([+\-]?[\d.]+)%", text
    )
    m_net = re.search(
        r"energy_net\.sum\s+\|.*?\|\s+Δ\s+([+\-]?[\d.]+)%", text
    )
    if m_draw:
        result["energy_draw_sum_delta"] = float(m_draw.group(1))
    if m_regen:
        result["energy_regen_sum_delta"] = float(m_regen.group(1))
    if m_net:
        result["energy_net_sum_delta"] = float(m_net.group(1))

    # ── Life ratio – Rainflow (joint‑level averages) ──
    rf_sec = re.search(
        r"Rainflow - Joint별 분석:(.*?)(?:⚠️\s+Rainflow 가장)", text, re.DOTALL
    )
    if rf_sec:
        for m in re.finditer(
            r"Joint_(\d+)\s+\|\s+([\d.eE+\-]+)\s+\|\s+([\d.eE+\-]+)\s+\|\s+([\d.]+)x",
            rf_sec.group(1),
        ):
            j = int(m.group(1))
            result[f"rf_joint_{j}_ratio"] = float(m.group(4))

    # ── Life ratio – Fatpack (joint‑level averages) ──
    fp_sec = re.search(
        r"Fatpack - Joint별 분석:(.*?)(?:⚠️\s+Fatpack 가장)", text, re.DOTALL
    )
    if fp_sec:
        for m in re.finditer(
            r"Joint_(\d+)\s+\|\s+([\d.eE+\-]+)\s+\|\s+([\d.eE+\-]+)\s+\|\s+([\d.]+)x",
            fp_sec.group(1),
        ):
            j = int(m.group(1))
            result[f"fp_joint_{j}_ratio"] = float(m.group(4))

    return result


def collect_all_data() -> dict:
    """data[dim_key][scale] = {metrics…}"""
    from collections import defaultdict

    data = defaultdict(dict)
    for txt in sorted(RESULTS_DIR.glob("comparison_*par*.txt")):
        dim_key, scale = identify_file(txt.name)
        if dim_key is None:
            print(f"  SKIP: {txt.name}")
            continue
        metrics = parse_comparison_file(txt)
        data[dim_key][scale] = metrics
        print(f"  OK: {dim_key}  scale={scale}  ({len(metrics)} fields)")
    return data


# ─── Plot helpers ────────────────────────────────────────────────────
def _weakest_annotations(ax, scales, data_dim, method):
    """Annotate the weakest joint at each noise scale."""
    for s in scales:
        best_j, best_r = -1, 0
        for j in range(7):
            r = data_dim[s].get(f"{method}_joint_{j}_ratio", 0)
            if r > best_r:
                best_r = r
                best_j = j
        if best_j >= 0 and best_r > 1:
            ax.annotate(
                f"Joint {best_j}\n{best_r:,.1f}x",
                xy=(s, best_r),
                fontsize=7.5,
                textcoords="offset points",
                xytext=(0, 14),
                ha="center",
                fontweight="bold",
                bbox=dict(
                    boxstyle="round,pad=0.3",
                    facecolor="lightyellow",
                    edgecolor="gray",
                    alpha=0.85,
                ),
            )


def plot_life_ratio(data, dim_key, method="rf"):
    """Joint‑wise life ratio vs noise scale (log y)."""
    label = DIM_LABELS[dim_key]
    method_name = "Rainflow" if method == "rf" else "Fatpack"

    fig, ax = plt.subplots(figsize=(12, 7))
    scales = sorted(data[dim_key].keys())

    for j in range(7):
        xs, ys = [], []
        for s in scales:
            r = data[dim_key][s].get(f"{method}_joint_{j}_ratio")
            if r is not None:
                xs.append(s)
                ys.append(r)
        if ys:
            ax.plot(
                xs, ys, "o-",
                color=JOINT_COLORS[j],
                label=f"Joint {j}",
                linewidth=2,
                markersize=6,
            )

    _weakest_annotations(ax, scales, data[dim_key], method)

    ax.set_yscale("log")
    ax.axhline(y=1, color="gray", linestyle="--", alpha=0.5, linewidth=1)
    ax.set_xlabel(f"noise scale (raw)", fontsize=12)
    ax.set_ylabel("Life ratio (x, log scale)", fontsize=12)
    ax.set_title(
        f"Life Ratio vs Noise Scale (log)\n(Top: weakest joint & life ratio) — {method_name}",
        fontsize=14,
        fontweight="bold",
        color="#1a5276",
    )
    ax.set_xticks(scales)
    ax.set_xticklabels([str(s) for s in scales])
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_energy_change(data, dim_key):
    """Energy draw & regen delta% bar chart (all bars annotated)."""
    label = DIM_LABELS[dim_key]

    fig, ax = plt.subplots(figsize=(10, 6))
    scales = sorted(data[dim_key].keys())

    x_labels = ["0"] + [str(s) for s in scales]
    draw_d = [0.0] + [
        data[dim_key][s].get("energy_draw_sum_delta", 0.0) for s in scales
    ]
    regen_d = [0.0] + [
        data[dim_key][s].get("energy_regen_sum_delta", 0.0) for s in scales
    ]

    x = np.arange(len(x_labels))
    w = 0.35

    bars_draw = ax.bar(x - w / 2, draw_d, w,
                       label="draw_sum delta%", color="#DAA520", alpha=0.85)
    bars_regen = ax.bar(x + w / 2, regen_d, w,
                        label="regen_sum delta%", color="#5B9BD5", alpha=0.85)

    for bar, v in zip(bars_draw, draw_d):
        if v == 0:
            continue
        ax.text(bar.get_x() + bar.get_width() / 2,
                v + (1.0 if v >= 0 else -1.0),
                f"{v:+.1f}%", ha="center",
                va="bottom" if v >= 0 else "top",
                fontsize=7.5, fontweight="bold")

    for bar, v in zip(bars_regen, regen_d):
        if v == 0:
            continue
        ax.text(bar.get_x() + bar.get_width() / 2,
                v + (1.0 if v >= 0 else -1.0),
                f"{v:+.1f}%", ha="center",
                va="bottom" if v >= 0 else "top",
                fontsize=7.5, fontweight="bold")

    ax.axhline(y=0, color="#DAA520", linestyle="--", alpha=0.5)
    ax.set_xlabel("noise scale (raw)", fontsize=12)
    ax.set_ylabel("Change (%)", fontsize=12)
    ax.set_title(
        f"Energy Change (16-step sampling)\n{label}",
        fontsize=14, fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels)
    ax.legend(loc="upper left", fontsize=10)
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    return fig


def plot_energy_net(data, dim_key):
    """Energy net delta% bar chart (separate file)."""
    label = DIM_LABELS[dim_key]

    fig, ax = plt.subplots(figsize=(10, 6))
    scales = sorted(data[dim_key].keys())

    x_labels = ["0"] + [str(s) for s in scales]
    net_d = [0.0] + [
        data[dim_key][s].get("energy_net_sum_delta", 0.0) for s in scales
    ]

    x = np.arange(len(x_labels))
    colors = ["#7B68AE" if v >= 0 else "#c0392b" for v in net_d]

    bars = ax.bar(x, net_d, 0.55, color=colors, alpha=0.85)

    for bar, v in zip(bars, net_d):
        if v == 0:
            continue
        ax.text(bar.get_x() + bar.get_width() / 2,
                v + (1.5 if v >= 0 else -3.5),
                f"{v:+.1f}%", ha="center",
                va="bottom" if v >= 0 else "top",
                fontsize=8, fontweight="bold")

    ax.axhline(y=0, color="gray", linestyle="--", alpha=0.5)
    ax.set_xlabel("noise scale (raw)", fontsize=12)
    ax.set_ylabel("net energy change (%)", fontsize=12)
    ax.set_title(
        f"Net Energy Change (energy_net.sum delta%)\n{label}\n"
        r"$\it{Note: baseline\ is\ negative,\ so\ \%\ can\ be\ counterintuitive}$",
        fontsize=12, fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels)
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    return fig


def plot_success_rate(data, dim_key):
    """Success rate bars with baseline dashed line."""
    label = DIM_LABELS[dim_key]

    fig, ax = plt.subplots(figsize=(10, 6))
    scales = sorted(data[dim_key].keys())

    baseline_sr = None
    for s in scales:
        v = data[dim_key][s].get("success_before")
        if v is not None:
            baseline_sr = v
            break

    srs = [data[dim_key][s].get("success_after", 0.0) for s in scales]
    x_labels = [str(s) for s in scales]
    x = np.arange(len(x_labels))

    ax.bar(x, srs, color="#77BB77", edgecolor="#4a7c4a", width=0.6)
    ax.plot(x, srs, "o-", color="#2d5a2d", linewidth=2, markersize=8, zorder=5)

    for xi, sr in zip(x, srs):
        ax.text(
            xi, sr + 0.8, f"{sr:.1f}%",
            ha="center", va="bottom",
            fontsize=11, fontweight="bold", color="#1a5276",
        )

    if baseline_sr is not None:
        ax.axhline(
            y=baseline_sr, color="red", linestyle="--", linewidth=2, alpha=0.7,
            label=f"Baseline (no noise): {baseline_sr:.1f}%",
        )
        ax.legend(loc="lower left", fontsize=10)

    ax.set_ylim(0, 100)
    ax.set_xlabel(f"Noise Scale ({label})", fontsize=12)
    ax.set_ylabel("Success Rate (%)", fontsize=12)
    ax.set_title(
        f"Task Success Rate vs Noise Scale\n{label}",
        fontsize=14, fontweight="bold", color="#1a5276",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(x_labels)
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    return fig


# ─── Derived metrics ─────────────────────────────────────────────────
def _mean_life_ratio(data_dim_scale: dict, method: str) -> float:
    """Mean life ratio across Joint 0-6 for one (dim, scale)."""
    vals = []
    for j in range(7):
        r = data_dim_scale.get(f"{method}_joint_{j}_ratio")
        if r is not None:
            vals.append(r)
    return float(np.mean(vals)) if vals else np.nan


def _max_life_ratio(data_dim_scale: dict, method: str):
    """(joint_id, ratio) of the weakest joint."""
    best_j, best_r = -1, 0
    for j in range(7):
        r = data_dim_scale.get(f"{method}_joint_{j}_ratio", 0)
        if r > best_r:
            best_r = r
            best_j = j
    return best_j, best_r


# ─── Combined plots ──────────────────────────────────────────────────
DIM_LINE_STYLES = {
    "action.x": ("o-", "#1f77b4"),
    "action.y": ("s-", "#ff7f0e"),
    "action.z": ("^-", "#2ca02c"),
    "action.axis_angle1": ("o-", "#d62728"),
    "action.axis_angle2": ("s-", "#9467bd"),
    "action.axis_angle3": ("^-", "#8c564b"),
}


def plot_combined_success_rate(data, dim_keys, title_prefix):
    """Overlay success rate lines for multiple dimensions."""
    fig, ax = plt.subplots(figsize=(11, 6))

    baseline_sr = None
    for dk in dim_keys:
        scales = sorted(data[dk].keys())
        srs = [data[dk][s].get("success_after", np.nan) for s in scales]
        marker, color = DIM_LINE_STYLES[dk]

        if baseline_sr is None:
            for s in scales:
                v = data[dk][s].get("success_before")
                if v is not None:
                    baseline_sr = v
                    break

        ax.plot(scales, srs, marker, color=color, linewidth=2, markersize=7,
                label=DIM_LABELS[dk])
        for s, sr in zip(scales, srs):
            ax.annotate(f"{sr:.1f}", xy=(s, sr), fontsize=7,
                        textcoords="offset points", xytext=(0, 8), ha="center")

    if baseline_sr is not None:
        ax.axhline(y=baseline_sr, color="red", linestyle="--", linewidth=2,
                   alpha=0.7, label=f"Baseline: {baseline_sr:.1f}%")

    ax.set_ylim(0, 100)
    ax.set_xlabel("Noise Scale", fontsize=12)
    ax.set_ylabel("Success Rate (%)", fontsize=12)
    ax.set_title(f"Success Rate Comparison — {title_prefix}",
                 fontsize=14, fontweight="bold", color="#1a5276")
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_combined_energy(data, dim_keys, title_prefix):
    """Overlay energy draw & regen delta% lines for multiple dimensions."""
    fig, ax = plt.subplots(figsize=(11, 6))

    for dk in dim_keys:
        scales = sorted(data[dk].keys())
        marker, color = DIM_LINE_STYLES[dk]
        short = DIM_LABELS[dk].split("(")[0].strip()

        draw_d = [data[dk][s].get("energy_draw_sum_delta", np.nan) for s in scales]
        regen_d = [data[dk][s].get("energy_regen_sum_delta", np.nan) for s in scales]

        ax.plot(scales, draw_d, marker, color=color, linewidth=2.5, markersize=7,
                label=f"{short} (draw)")
        ax.plot(scales, regen_d, "--", color=color, linewidth=1.5, alpha=0.55,
                label=f"{short} (regen)")

        for s, dv, rv in zip(scales, draw_d, regen_d):
            if not np.isnan(dv):
                ax.annotate(f"{dv:+.1f}", xy=(s, dv), fontsize=6.5,
                            textcoords="offset points", xytext=(0, 7),
                            ha="center", color=color, fontweight="bold")
            if not np.isnan(rv):
                ax.annotate(f"{rv:+.1f}", xy=(s, rv), fontsize=5.5,
                            textcoords="offset points", xytext=(0, -10),
                            ha="center", color=color, alpha=0.7)

    ax.axhline(y=0, color="gray", linestyle=":", alpha=0.5)
    ax.set_xlabel("Noise Scale", fontsize=12)
    ax.set_ylabel("Change from Baseline (%)", fontsize=12)
    ax.set_title(f"Energy Change Comparison — {title_prefix}\n(solid = draw, dashed = regen)",
                 fontsize=14, fontweight="bold")
    ax.legend(fontsize=8, ncol=2, loc="upper left")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_combined_life_ratio(data, dim_keys, method, title_prefix):
    """Mean life ratio (across joints) per dimension, overlaid."""
    method_name = "Rainflow" if method == "rf" else "Fatpack"
    fig, ax = plt.subplots(figsize=(11, 7))

    for dk in dim_keys:
        scales = sorted(data[dk].keys())
        means = [_mean_life_ratio(data[dk][s], method) for s in scales]
        marker, color = DIM_LINE_STYLES[dk]
        ax.plot(scales, means, marker, color=color, linewidth=2.5, markersize=7,
                label=f"{DIM_LABELS[dk]} (mean)")

        for s, m_val in zip(scales, means):
            if not np.isnan(m_val):
                ax.annotate(f"{m_val:.1f}x", xy=(s, m_val), fontsize=7,
                            textcoords="offset points", xytext=(0, 10),
                            ha="center",
                            bbox=dict(boxstyle="round,pad=0.2",
                                      facecolor="white", alpha=0.7, edgecolor="none"))

    ax.set_yscale("log")
    ax.axhline(y=1, color="gray", linestyle="--", alpha=0.5)
    ax.set_xlabel("Noise Scale", fontsize=12)
    ax.set_ylabel("Mean Life Ratio (x, log)", fontsize=12)
    ax.set_title(
        f"Mean Life Ratio Comparison — {title_prefix} ({method_name})\n"
        f"(averaged across Joint 0–6)",
        fontsize=14, fontweight="bold", color="#1a5276")
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_combined_weakest_joint(data, dim_keys, method, title_prefix):
    """Weakest (max) joint life ratio per dimension, overlaid."""
    method_name = "Rainflow" if method == "rf" else "Fatpack"
    fig, ax = plt.subplots(figsize=(11, 7))

    for dk in dim_keys:
        scales = sorted(data[dk].keys())
        maxes = [_max_life_ratio(data[dk][s], method) for s in scales]
        ratios = [m[1] for m in maxes]
        marker, color = DIM_LINE_STYLES[dk]
        ax.plot(scales, ratios, marker, color=color, linewidth=2.5, markersize=7,
                label=DIM_LABELS[dk])

        for s, (wj, wr) in zip(scales, maxes):
            if wr > 1:
                ax.annotate(f"J{wj}\n{wr:,.0f}x", xy=(s, wr), fontsize=6.5,
                            textcoords="offset points", xytext=(0, 12),
                            ha="center", fontweight="bold",
                            bbox=dict(boxstyle="round,pad=0.2",
                                      facecolor="lightyellow", edgecolor="gray",
                                      alpha=0.8))

    ax.set_yscale("log")
    ax.axhline(y=1, color="gray", linestyle="--", alpha=0.5)
    ax.set_xlabel("Noise Scale", fontsize=12)
    ax.set_ylabel("Weakest Joint Life Ratio (x, log)", fontsize=12)
    ax.set_title(
        f"Weakest Joint Life Ratio — {title_prefix} ({method_name})",
        fontsize=14, fontweight="bold", color="#1a5276")
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    return fig


def plot_position_vs_rotation_summary(data):
    """Side-by-side bar chart: position mean vs rotation mean at each shared scale."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))

    # Compute averages across dims for each category
    pos_scales = sorted(data[POSITION_DIMS[0]].keys())
    rot_scales = sorted(data[ROTATION_DIMS[0]].keys())

    def _avg_across_dims(dim_keys, metric_key):
        scales = sorted(data[dim_keys[0]].keys())
        out = []
        for s in scales:
            vals = [data[dk][s].get(metric_key, np.nan) for dk in dim_keys
                    if s in data[dk]]
            out.append(np.nanmean(vals))
        return scales, out

    # Panel 1: Success Rate
    ax = axes[0]
    ps, pv = _avg_across_dims(POSITION_DIMS, "success_after")
    rs, rv = _avg_across_dims(ROTATION_DIMS, "success_after")
    ax.plot(range(len(ps)), pv, "o-", color="#1f77b4", linewidth=2, label="Position (x,y,z avg)")
    ax.plot(range(len(rs)), rv, "s-", color="#d62728", linewidth=2, label="Rotation (aa1,2,3 avg)")
    baseline = data[POSITION_DIMS[0]][ps[0]].get("success_before", 88.5)
    ax.axhline(y=baseline, color="red", linestyle="--", alpha=0.5,
               label=f"Baseline: {baseline:.1f}%")
    ax.set_xticks(range(max(len(ps), len(rs))))
    ax.set_xticklabels([f"s{i+1}" for i in range(max(len(ps), len(rs)))])
    ax.set_xlabel("Scale index (1–6)")
    ax.set_ylabel("Success Rate (%)")
    ax.set_title("Success Rate", fontweight="bold")
    ax.set_ylim(0, 100)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # Panel 2: Energy Draw
    ax = axes[1]
    ps, pv = _avg_across_dims(POSITION_DIMS, "energy_draw_sum_delta")
    rs, rv = _avg_across_dims(ROTATION_DIMS, "energy_draw_sum_delta")
    ax.plot(range(len(ps)), pv, "o-", color="#1f77b4", linewidth=2, label="Position")
    ax.plot(range(len(rs)), rv, "s-", color="#d62728", linewidth=2, label="Rotation")
    ax.axhline(y=0, color="gray", linestyle=":", alpha=0.5)
    ax.set_xticks(range(max(len(ps), len(rs))))
    ax.set_xticklabels([f"s{i+1}" for i in range(max(len(ps), len(rs)))])
    ax.set_xlabel("Scale index (1–6)")
    ax.set_ylabel("Energy Draw Change (%)")
    ax.set_title("Energy Draw Delta%", fontweight="bold")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # Panel 3: Mean Life Ratio (Rainflow)
    ax = axes[2]
    for cat_label, dim_keys, color in [
        ("Position", POSITION_DIMS, "#1f77b4"),
        ("Rotation", ROTATION_DIMS, "#d62728"),
    ]:
        scales = sorted(data[dim_keys[0]].keys())
        all_means = []
        for s in scales:
            vals = [_mean_life_ratio(data[dk][s], "rf") for dk in dim_keys
                    if s in data[dk]]
            all_means.append(np.nanmean(vals))
        ax.plot(range(len(scales)), all_means, "o-", color=color, linewidth=2,
                label=cat_label)
    ax.set_yscale("log")
    ax.axhline(y=1, color="gray", linestyle="--", alpha=0.5)
    ax.set_xticks(range(max(len(pos_scales), len(rot_scales))))
    ax.set_xticklabels([f"s{i+1}" for i in range(max(len(pos_scales), len(rot_scales)))])
    ax.set_xlabel("Scale index (1–6)")
    ax.set_ylabel("Mean Life Ratio (log)")
    ax.set_title("Life Ratio (Rainflow)", fontweight="bold")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    fig.suptitle("Position vs Rotation — Overall Summary",
                 fontsize=16, fontweight="bold", color="#1a5276", y=1.02)
    fig.tight_layout()
    return fig


# ─── Main ────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print(" Collecting data from comparison txt files ...")
    print("=" * 60)

    data = collect_all_data()

    print(f"\nDimensions found: {len(data)}")
    for dk in sorted(data.keys()):
        print(f"  {dk}: {sorted(data[dk].keys())}")

    all_dims = POSITION_DIMS + ROTATION_DIMS
    generated = []

    # ── Per‑dimension plots (24) ──
    for dim_key in all_dims:
        if dim_key not in data or not data[dim_key]:
            print(f"\n  SKIP {dim_key}: no data")
            continue

        dim_short = dim_key.split(".")[-1]
        cat = "position" if dim_key in POSITION_DIMS else "rotation"
        print(f"\n  Plotting {dim_key} …")

        for method in ("rf", "fp"):
            mname = "rainflow" if method == "rf" else "fatpack"
            fig = plot_life_ratio(data, dim_key, method=method)
            p = PLOTS_DIR / f"{cat}_life_ratio_{mname}_{dim_short}.png"
            fig.savefig(p, dpi=150); plt.close(fig)
            generated.append(p.name)

        fig = plot_energy_change(data, dim_key)
        p = PLOTS_DIR / f"{cat}_energy_change_{dim_short}.png"
        fig.savefig(p, dpi=150); plt.close(fig)
        generated.append(p.name)

        # energy_net in separate subfolder
        net_dir = PLOTS_DIR / "energy_net"
        net_dir.mkdir(parents=True, exist_ok=True)
        fig = plot_energy_net(data, dim_key)
        p = net_dir / f"{cat}_energy_net_{dim_short}.png"
        fig.savefig(p, dpi=150); plt.close(fig)
        generated.append(f"energy_net/{p.name}")

        fig = plot_success_rate(data, dim_key)
        p = PLOTS_DIR / f"{cat}_success_rate_{dim_short}.png"
        fig.savefig(p, dpi=150); plt.close(fig)
        generated.append(p.name)

    # ── Combined plots ──
    print("\n  Generating combined plots …")

    for cat, dim_keys, label in [
        ("position", POSITION_DIMS, "Position (x, y, z)"),
        ("rotation", ROTATION_DIMS, "Rotation (roll, pitch, yaw)"),
    ]:
        avail = [dk for dk in dim_keys if dk in data and data[dk]]
        if not avail:
            continue

        fig = plot_combined_success_rate(data, avail, label)
        p = PLOTS_DIR / f"{cat}_combined_success_rate.png"
        fig.savefig(p, dpi=150); plt.close(fig)
        generated.append(p.name)

        fig = plot_combined_energy(data, avail, label)
        p = PLOTS_DIR / f"{cat}_combined_energy.png"
        fig.savefig(p, dpi=150); plt.close(fig)
        generated.append(p.name)

        for method in ("rf", "fp"):
            mname = "rainflow" if method == "rf" else "fatpack"

            fig = plot_combined_life_ratio(data, avail, method, label)
            p = PLOTS_DIR / f"{cat}_combined_mean_life_ratio_{mname}.png"
            fig.savefig(p, dpi=150); plt.close(fig)
            generated.append(p.name)

            fig = plot_combined_weakest_joint(data, avail, method, label)
            p = PLOTS_DIR / f"{cat}_combined_weakest_joint_{mname}.png"
            fig.savefig(p, dpi=150); plt.close(fig)
            generated.append(p.name)

    # Position vs Rotation overview
    fig = plot_position_vs_rotation_summary(data)
    p = PLOTS_DIR / "overview_position_vs_rotation.png"
    fig.savefig(p, dpi=150, bbox_inches="tight"); plt.close(fig)
    generated.append(p.name)

    # ── Summary table to stdout ──
    print(f"\n{'=' * 80}")
    print(" DATA SUMMARY")
    print(f"{'=' * 80}")
    for dk in all_dims:
        if dk not in data:
            continue
        scales = sorted(data[dk].keys())
        print(f"\n  {DIM_LABELS[dk]}")
        print(f"  {'Scale':>6s}  {'SR%':>6s}  {'Draw%':>7s}  {'Regen%':>7s}"
              f"  {'RF mean':>8s}  {'FP mean':>8s}  {'RF worst':>10s}  {'FP worst':>10s}")
        print(f"  {'-'*72}")
        for s in scales:
            d = data[dk][s]
            sr = d.get("success_after", np.nan)
            draw = d.get("energy_draw_sum_delta", np.nan)
            regen = d.get("energy_regen_sum_delta", np.nan)
            rf_m = _mean_life_ratio(d, "rf")
            fp_m = _mean_life_ratio(d, "fp")
            wj_rf, wr_rf = _max_life_ratio(d, "rf")
            wj_fp, wr_fp = _max_life_ratio(d, "fp")
            print(f"  {s:6.2f}  {sr:5.1f}%  {draw:+6.1f}%  {regen:+6.1f}%"
                  f"  {rf_m:7.1f}x  {fp_m:7.1f}x"
                  f"  J{wj_rf}={wr_rf:7.1f}x  J{wj_fp}={wr_fp:7.1f}x")

    print(f"\n{'=' * 60}")
    print(f" Generated {len(generated)} plots in {PLOTS_DIR}/")
    for name in generated:
        print(f"   {name}")
    print("=" * 60)


if __name__ == "__main__":
    main()
